### ISSUE TITLE
Does not work on Linux

### ISSUE THREAD

**Issue by jeffboy70** [v-briese/platform-switcher#1]
When I install this plugin and restart discord, it shows the loading screen with the Windows titlebar then it freezes and stops loading, and if I change the value in `Settings.jsx` to OSX or Linux it does the same thing.

System Details:
Operating System: Arch Linux
KDE Plasma Version: 5.21.5
KDE Frameworks Version: 5.82.0
Qt Version: 5.15.2
Kernel Version: 5.12.8-zen1-1-zen
OS Type: 64-bit
Graphics Platform: X11
Processors: 2 × Intel® Pentium® CPU G4400 @ 3.30GHz
Memory: 11.7 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 660/PCIe/SSE2

**Comment by v-briese** [comment]
Hm... Try launching discord through a terminal, then there should be output text. Send that back to me.

**Comment by jeffboy70** [comment]
```
Discord 0.0.15
Quitting secondary instance.
(node:595989) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

(discord:595989): Gtk-WARNING **: 13:12:56.966: Theme parsing error: gtk-dark.css:9281:102: The :focused pseudo-class is deprecated. Use :focus instead.

(discord:595989): Gtk-WARNING **: 13:12:56.966: Theme parsing error: gtk-dark.css:9286:114: The :focused pseudo-class is deprecated. Use :focus instead.
Gtk-Message: 13:12:57.037: Failed to load module "appmenu-gtk-module"
➜  plugins git:(stable) ✗ discord
Discord 0.0.15
(node:596184) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

(discord:596184): Gtk-WARNING **: 13:13:31.107: Theme parsing error: gtk-dark.css:9281:102: The :focused pseudo-class is deprecated. Use :focus instead.

(discord:596184): Gtk-WARNING **: 13:13:31.107: Theme parsing error: gtk-dark.css:9286:114: The :focused pseudo-class is deprecated. Use :focus instead.
Gtk-Message: 13:13:31.141: Failed to load module "appmenu-gtk-module"
Starting app.
Starting updater.
[Modules] Modules initializing
[Modules] Distribution: remote
[Modules] Host updates: enabled
[Modules] Module updates: enabled
[Modules] Module install path: /home/jefferson/.config/discord/0.0.15/modules
[Modules] Module installed file path: /home/jefferson/.config/discord/0.0.15/modules/installed.json
[Modules] Module download path: /home/jefferson/.config/discord/0.0.15/modules/pending
[Modules] No updates to install
[Modules] Checking for host updates.
[Modules] Host is up to date.
[Modules] Checking for module updates at https://discord.com/api/modules/stable/versions.json
[Modules] No module updates available.
``` 
It just stops there and does nothing else.

**Comment by v-briese** [comment]
It looks like there's a module required specifically for Linux (or at least, your branch of Linux). If I had to guess, Discord doesn't bother doing what it needs to with that module because it thinks your on the web platform (0 is Windows, 1 is OSX, 2 is Linux, and 3 or null is Web). Does Discord work properly if you set the `platform` setting to 2?

**Comment by jeffboy70** [comment]
Sorry for super late reply, just tried it and it does.

**Comment by v-briese** [comment]
Unfortunately, there's nothing I can do about this. Discord simply works differently on Linux than it does on other platforms.
